language: python

dist: xenial

sudo: true

services:
- mysql

addons:
  apt_packages:
     - libcups2-dev

branches:
  only:
  - develop

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls

before_script:
- flake8 edc_form_label
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=edc_form_label manage.py test

after_success:
- coveralls

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.7
      env: TOXENV=py37-djangotrunk
    - python: 3.8
      env: TOXENV=py38-djangotrunk
